### ISSUE TITLE
misc/decode_runnie.py:57: RuntimeWarning: invalid value encountered in log1p return np.exp(y * np.log1p(x))

### ISSUE THREAD

**Issue by damientully** [nanoporetech/flappie#44] opened 2019-10-14 09:46 UTC
Hi Tim,

I seem to be getting this error when running runnie. Any suggestions? 

`python3 misc/decode_runnie.py run12.run > Run12_runnie_basecalls.fa
misc/decode_runnie.py:57: RuntimeWarning: invalid value encountered in log1p
  return np.exp(y * np.log1p(x))
misc/decode_runnie.py:51: RuntimeWarning: invalid value encountered in power
  a = np.power((x - 1) / scale, shape)
misc/decode_runnie.py:74: RuntimeWarning: invalid value encountered in greater
  run_mode = np.where((run_mode > 1) & (pmf_mode_m1 > pmf_mode),
misc/decode_runnie.py:57: RuntimeWarning: divide by zero encountered in log1p
  return np.exp(y * np.log1p(x))
misc/decode_runnie.py:57: RuntimeWarning: invalid value encountered in log1p
  return np.exp(y * np.log1p(x))
misc/decode_runnie.py:51: RuntimeWarning: invalid value encountered in power
  a = np.power((x - 1) / scale, shape)
misc/decode_runnie.py:74: RuntimeWarning: invalid value encountered in greater
  run_mode = np.where((run_mode > 1) & (pmf_mode_m1 > pmf_mode),
misc/decode_runnie.py:57: RuntimeWarning: divide by zero encountered in log1p
  return np.exp(y * np.log1p(x))
misc/decode_runnie.py:86: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  base_vec[base_vec == b] = i`

**Comment by tmassingham-ont** [comment] 2019-10-14 09:57
Hello. The `RuntimeWarning` are nuisance and can be ignored.  
The root cause is that `np.where` evaluates both expressions given to it and then select elements for the result based on the condition given.  In this case the condition guards against invalid values (e.g. taking log of a non-positive number), so they do not affect the result, but are still evaluated.

I'm not so sure about the `FutureWarning`; which versions of Python and NumPy are you using please?

**Comment by damientully** [comment] 2019-10-14 10:05
Thanks. Python v.3.6.0 and NumPy v.1.16.1

**Comment by tmassingham-ont** [comment] 2019-10-14 10:43
I've pushed a patch to ignore the `RuntimeWarning`.  I'm unable to reproduce the `FutureWarning` using Python 3.5.2 or 3.6.8 with NumPy 1.16.1 (and several other versions).  Do you have access to any other version of Python 3 you could test with please?

**Comment by damientully** [comment] 2019-10-14 11:17
Running now with a different version of Python 3. Get another FutureWarning aswell. 

`misc/decode_runnie.py:96: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  base_vec[base_vec == b] = i`

**Comment by damientully** [comment] 2019-10-14 13:20
It seems to stall at the same read every time. Can I send you the file to see if you can reproduce it?

**Comment by tmassingham-ont** [comment] 2019-10-15 09:36
I'd love to look at it.  You can email me at `tim.massingham` at the obvious `nanoporetech` domain.

**Comment by damientully** [comment] 2019-10-15 09:50
Just to sent you an email. Thanks!

**Comment by tmassingham-ont** [comment] 2019-10-16 08:41
Received, thanks.  The `FutureWarning` is triggered by an empty read, with no data to base call.  I've add a guard to `decode_runnie.py` to report and ignore such reads.

**Comment by tmassingham-ont** [comment] 2019-10-16 11:48
@damientully reports success, closing issue.

**Closed by tmassingham-ont** 2019-10-16 11:48 UTC
